WebApplication6/Controllers/EventController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Rotativa;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using WebApplication6.Models;
using WebApplication6.ViewModels;

namespace WebApplication6.Controllers
{
    public class EventController : Controller
    {
        private dbSchoolsEntities _db = new dbSchoolsEntities();
        public List<Curs> cursuri = new List<Curs>();
        public List<SelectListItem> Courses { get; set; }
        EventViewModel ev = new EventViewModel();

        protected ApplicationDbContext ApplicationDbContext { get; set; }


        protected UserManager<ApplicationUser> UserManager { get; set; }


        public Events _event = new Events();
        ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

        public EventController(List<Curs> cursuri, ApplicationDbContext applicationDbContext, UserManager<ApplicationUser> userManager, Events @event)
        {
            this.cursuri = cursuri;
            ApplicationDbContext = applicationDbContext;
            UserManager = userManager;
            _event = @event;
            this.ApplicationDbContext = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
        }

        public EventController()
        {
        }

        Profesor profesor;
        Student student;
        public Action Populate()
        {
            List<Profesor> profesori = new List<Profesor>(_db.Profesori.ToList());
            List<Curs> _cursuri = new List<Curs>(_db.Cursuri.ToList());
            List<Student> students = new List<Student>(_db.Studenti.ToList());
            List<InscriereCursuri> inscriere = new List<InscriereCursuri>(_db.InscriereCursuri.ToList());
            if (User.IsInRole("Student"))
            {
                foreach (Student student_ in students)
                {
                    if (user.Id == student_.GUID)
                        student = student_;
                }
                foreach (Curs curs_ in _cursuri)
                {
                    foreach (InscriereCursuri inscriereCursuri in inscriere)
                    {
                        if (student.Id == inscriereCursuri.StudId && inscriereCursuri.ClassId == curs_.CursId)
                            cursuri.Add(curs_);
                    }

                }
            }
            if (User.IsInRole("Profesor"))
            {
                foreach (Profesor prof in profesori)
                {
                    if (user.Id == prof.Guid)
                        profesor = prof;

                }

                foreach (Curs curs_ in _cursuri)
                {
                    if (curs_.ProfId == profesor.Id)
                        cursuri.Add(curs_);
                }

            }

            var items = from Curs curs in cursuri
                        select new SelectListItem { Value = curs.CursId.ToString(), Text = curs.Nume };

            ViewData["Classlist"] = items;

            return null;


        }
        [HttpPost]
        public  Action SetRoomsToStatus(String JSONString )
        {
            List<Sala> sali = new List<Sala>(_db.Sali.ToList());
            List<Events> events = new List<Events>(_db.Events.ToList());
            

            DateTimeOffset date = Convert.ToDateTime(JSONString);



            foreach (Events ev in events)
            {
                    if(ev.Start_time<date && ev.End_time > date)
                    {
                    _db.Sali.FirstOrDefault(x => x.Id == ev.SalaId).Libera = false;
                    _db.SaveChanges();
                    }
           
            };
            return null;


        }
        [HttpPost]
        public Action SetRoomsToStatusEnd( String JSONStringEnd)
        {
            List<Sala> sali = new List<Sala>(_db.Sali.ToList());
            List<Events> events = new List<Events>(_db.Events.ToList());


            DateTimeOffset endDate = Convert.ToDateTime(JSONStringEnd);



            foreach (Events ev in events)
            {
               if (ev.Start_time < endDate && ev.End_time > endDate)
                 {
                _db.Sali.FirstOrDefault(x => x.Id == ev.SalaId).Libera = false;
                _db.SaveChanges();
                }

            };
            return null;


        }
        public ActionResult GetSala(int id)
        {
            List<Sala> sali = new List<Sala>(_db.Sali.ToList());
            List<Curs> _cursuri = new List<Curs>(_db.Cursuri.ToList());
            Curs curs = _cursuri.Find(x => x.CursId == id);
            List<InscriereCursuri> inscrieri = new List<InscriereCursuri>(_db.InscriereCursuri.ToList());

            List<SelectListItem> items = new List<SelectListItem>();
            var inscrieri_ = inscrieri.GroupBy(x => x)
              .Where(g => g.Count() > 1)
              .ToDictionary(x => x.Key, y => y.Count());
            if (inscrieri.Count() == 0)
            {
                foreach (Sala sala in sali)
                {
                    if (sala.Libera == true)
                        items.Add(new SelectListItem() { Text = sala.Nume, Value = sala.Id.ToString() });
                }
            }
            else {
                InscriereCursuri insc = inscrieri.Find(x => x.ClassId == curs.CursId);
                
                
                    inscrieri_.TryGetValue(insc, out int number);
                
                List<Sala> saliFiltrate = sali.FindAll(x => x.Capacitate >= number && x.Libera == true);


                foreach (Sala sala in saliFiltrate)
                {
                    items.Add(new SelectListItem() { Text = sala.Nume, Value = sala.Id.ToString() });

                } }


            return Json(items, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetPCSala(int id)
        {
            List<Sala> sali = new List<Sala>(_db.Sali.ToList());
            List<Curs> _cursuri = new List<Curs>(_db.Cursuri.ToList());
            Curs curs = _cursuri.Find(x => x.CursId == id);
            List<InscriereCursuri> inscrieri = new List<InscriereCursuri>(_db.InscriereCursuri.ToList());

            List<SelectListItem> items = new List<SelectListItem>();
            var inscrieri_ = inscrieri.GroupBy(x => x)
              .Where(g => g.Count() > 1)
              .ToDictionary(x => x.Key, y => y.Count());
            if (inscrieri.Count() == 0 )
            {
                var data = sali
               .Where(x => x.Libera == true && x.PC == true)
               .Select(l => new { Value = l.Id.ToString(), Text = l.Nume });
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            else 
            {
                InscriereCursuri insc = inscrieri.Find(x => x.ClassId == curs.CursId);
                inscrieri_.TryGetValue(insc, out int number);

                var data = sali.Where(x => x.Capacitate >= number && x.Libera == true && x.PC == true).Select(l => new { Value = l.Id.ToString(), Text = l.Nume });
                return Json(data, JsonRequestBehavior.AllowGet);

            }
        }
        public ActionResult GetVideoSala(int id)
        {
            List<Sala> sali = new List<Sala>(_db.Sali.ToList());
            List<Curs> _cursuri = new List<Curs>(_db.Cursuri.ToList());
            Curs curs = _cursuri.Find(x => x.CursId == id);
            List<InscriereCursuri> inscrieri = new List<InscriereCursuri>(_db.InscriereCursuri.ToList());

            List<SelectListItem> items = new List<SelectListItem>();
            var inscrieri_ = inscrieri.GroupBy(x => x)
              .Where(g => g.Count() > 1)
              .ToDictionary(x => x.Key, y => y.Count());
            if (inscrieri.Count() == 0)
            {
                var data = sali
               .Where(x => x.Libera == true && x.Echipament_Video == true)
               .Select(l => new { Value = l.Id.ToString(), Text = l.Nume });
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            else
            {
                InscriereCursuri insc = inscrieri.Find(x => x.ClassId == curs.CursId);
                inscrieri_.TryGetValue(insc, out int number);

                var data = sali.Where(x => x.Capacitate >= number && x.Libera == true && x.Echipament_Video == true).Select(l => new { Value = l.Id.ToString(), Text = l.Nume });
                return Json(data, JsonRequestBehavior.AllowGet);

            }
        }
        public ActionResult GetVideoPCSala(int id)
        {
            List<Sala> sali = new List<Sala>(_db.Sali.ToList());
            List<Curs> _cursuri = new List<Curs>(_db.Cursuri.ToList());
            Curs curs = _cursuri.Find(x => x.CursId == id);
            List<InscriereCursuri> inscrieri = new List<InscriereCursuri>(_db.InscriereCursuri.ToList());

            List<SelectListItem> items = new List<SelectListItem>();
            var inscrieri_ = inscrieri.GroupBy(x => x)
              .Where(g => g.Count() > 1)
              .ToDictionary(x => x.Key, y => y.Count());
            if (inscrieri.Count() == 0)
            {
                var data = sali
               .Where(x => x.Libera == true && x.Echipament_Video == true && x.PC == true)
               .Select(l => new { Value = l.Id.ToString(), Text = l.Nume });
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            else
            {
                InscriereCursuri insc = inscrieri.Find(x => x.ClassId == curs.CursId);

WebApplication6/Controllers/RoleController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{
    public class RoleController : Controller
    {
        private ApplicationRoleManager _roleManager;

        public RoleController()
        {
        }

        public RoleController(ApplicationRoleManager roleManager)
        {
            RoleManager = roleManager;

        }

        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        // GET: Role
        [Authorize(Roles = "Administrator")]

        public ActionResult Index()
        {
            List<RoleViewModel> list = new List<RoleViewModel>();
            foreach (var role in RoleManager.Roles)
            {
                list.Add(new RoleViewModel(role));
            }
            return View(list);
        }

        public ActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Administrator")]

        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel model)
        {
            var role = new ApplicationRole() { Name = model.Name };
            await RoleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Administrator")]

        public async Task<ActionResult> Edit(string Id)
        {
            var role = await RoleManager.FindByIdAsync(Id);
            return View(new RoleViewModel(role));
        }
        [HttpPost]
        public async Task<ActionResult>Edit(RoleViewModel model)
        {
            var role = new ApplicationRole() { Id = model.Id,Name = model.Name };
            await RoleManager.UpdateAsync(role);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Administrator")]

        public async Task<ActionResult> Details(string Id)
        {
            var role = await RoleManager.FindByIdAsync(Id);
            return View(new RoleViewModel(role));
        }
        [Authorize(Roles = "Administrator")]

        [HttpDelete]
        public async Task<ActionResult> Delete(string Id)
        {
            var role = await RoleManager.FindByIdAsync(Id);
            return View(new RoleViewModel(role));
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string Id)
        {
            var role = await RoleManager.FindByIdAsync(Id);
            await RoleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }

    }
}

WebApplication6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/jquery-3.4.1.js")
    @Scripts.Render("~/Scripts/moment.js");

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/fullcalendar")
    <link rel="stylesheet" type="text/css" href="~/styles/bootstrap4/bootstrap.min.css">
    <link href="~/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="~/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="~/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="~/plugins/OwlCarousel2-2.2.1/animate.css">
    <link rel="stylesheet" type="text/css" href="~/styles/main_styles.css">
    <link rel="stylesheet" type="text/css" href="~/styles/responsive.css">
    @RenderSection("scripts", required: false)
</head>

<body>
    <div class="header_container">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="header_content d-flex flex-row align-items-center justify-content-start">
                        <div class="logo_container">
                            <a href="#">
                                <div class="logo_text">Educat<span>Book</span></div>
                            </a>
                        </div>
                        <nav class="main_nav_contaner ml-auto">
                            <ul class="main_nav">
                                <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", "Index", new { @class = "nav-link active" })</li>
                                <li class="nav-item">@Html.ActionLink("Studenti", "Index", "Studenti", "Index", new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Profesori", "Index", "Profesori", "Index", new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Cursuri", "Index", "Cursuri", "Index", new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Roluri", "Index", "Role", "Index", new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Calendar", "Index", "Calendar", "Index", new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Prezente", "Index", "Prezente", "Index", new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Rezervari", "Create", "Event", "Create", new { @class = "nav-link" })</li>

                            </ul>

                            <!-- Hamburger -->


                            <div class="hamburger menu_mm">
                                <i class="fa fa-bars menu_mm" aria-hidden="true"></i>
                            </div>
                        </nav>

                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>


</body>
</html>